In [1]:
import pandas as pd
import numpy as np

In [2]:
merged = pd.read_csv('Mapping.csv',sep=',')

In [3]:
merged.head()

         AccNum GeneName
0          chrE     chrE
1     NM_017847     ODR4
2  NM_001003803    ATP5S
3  NM_001003800    BICD2
4     NM_016649     ESF1

In [6]:
array = ['NM_002224','NM_006885','NM_001080495','NM_001286554','NM_024036','NM_015175','NM_001033723','NM_015164','NM_021224','NM_001351643','NM_001271938','NM_014680','NM_007313','NM_001256666','NM_001319','NM_001349247','NM_012334','NM_018896','NM_004225','NM_001012761','NM_003502','NM_032482','NM_170606','NM_001321291','NM_032902','NM_001039111','NM_007111','NM_015335','NM_019121','NM_024490','NM_198868','NM_002653','NM_014853','NM_006766','NM_001040429','NM_022455','NM_003274','NM_004976','NM_178537','NM_032444','NM_017514','NM_001206999','NM_001330474','NM_001330660','NM_004569','NM_001304808','NM_001122772','NM_007038','NM_207370','NM_001319193','NM_019892','NM_032888','NM_003036','NM_001348990','NM_001287491','NM_001271','NM_020452','NM_001009944','NM_004747','NM_030912','NM_001130969','NM_015187','NM_003972','NM_003791','NM_001324321','NM_000332','NM_002850','NM_016228','NM_003028','NM_006699','NM_001318245','NM_032806','NM_005475','NM_000168','NM_139078','NM_015205','NM_001142640','NM_005632','NM_005631','NM_032223','NM_032221','NM_004938','NM_017758','NM_001286520','NM_198679','NM_145754','NM_018984','NM_001319238','NM_152594','NM_207395','NM_018949','NM_014856','NM_015656','NM_001320613','NM_006612','NM_001308207','NM_002972','NM_020218','NM_005197','NM_004631','NM_002419','NM_001289864','NM_001470','NM_000127','NM_006266','NM_004807','NM_032242','NM_001079514','NM_021831','NM_001289394','NM_015313','NM_007118','NM_173500','NM_002894','NM_001252100','NM_001199417','NM_001300801','NM_202002','NM_021216','NM_001322845','NM_015015','NM_002214','NM_022740','NM_020771','NM_032752','NM_145804','NM_015130','NM_152787','NM_021098','NM_001007233','NM_003325','NM_032552','NM_015350','NM_006734','NM_000641','NM_181832','NM_001128918','NM_005937','NM_201274','NM_007345','NM_005544','NM_001005850','NM_001304331','NM_006999','NM_004380','NM_014585','NM_006035','NM_007039','NM_002605','NM_001304815','NM_173593','NM_014671','NM_015447','NM_001258329','NM_000455','NM_006927','NM_198968','NM_014652','NM_004973','NM_016516','NM_024503','NM_032430','NM_018121','NM_001353693','NM_002841','NM_020695','NM_003780','NM_005781','NM_001349852','NM_014700','NM_133445','NM_001100588','NM_002333','NM_002073','NM_001407','NM_001349798','NM_001080414','NM_020718','NM_001127198','NM_001543','NM_001346413','NM_020245','NM_001099289','NM_014572','NM_003627','NM_001292025','NM_015049','NM_001100913','NM_199330','NM_001080410','NM_033517','NM_015878','NM_005121','NM_020223','NM_014712','NM_001351082','NM_058243','NM_021639','NM_001349451','NM_015210','NM_020808','NM_020759','NM_020209','NM_001163812','NM_032108','NM_006946','NM_001429','NM_020825','NM_020820','NM_005392','NM_001008701','NM_018013','NM_145725','NM_198236','NM_024940','NM_001330260','NM_005270','NM_001184889','NM_001130065','NM_001351850','NM_001037131','NM_014727']
merged.loc[merged['AccNum'].isin(array)]['GeneName'].tolist()

['ITPR3',
 'ZFHX3',
 'TNRC18',
 'USP49',
 'LRFN4',
 'NBEAL2',
 'ZNF704',
 'PLEKHM2',
 'ZNF462',
 'PPP6R2',
 'MEGF8',
 'KIAA0100',
 'ABL1',
 'FAM193A',
 'CSNK1G2',
 'TRAK1',
 'MYO10',
 'CACNA1G',
 'MFHAS1',
 'RGMB',
 'AXIN1',
 'DOT1L',
 'KMT2C',
 'USP36',
 'PPP1R16A',
 'TRIM71',
 'TFDP1',
 'MED13L',
 'PPP1R37',
 'ATP10A',
 'TBC1D9B',
 'PITX1',
 'SGSM2',
 'KAT6A',
 'PCDH17',
 'NSD1',
 'TRAPPC10',
 'KCNC1',
 'B4GALNT4',
 'SLX4',
 'PLXNA3',
 'CIT',
 'RNF10',
 'GBA2',
 'PIGH',
 'BRD1',
 'AGAP2',
 'ADAMTS5',
 'GPR153',
 'FBF1',
 'INPP5E',
 'COL27A1',
 'SKI',
 'NXPE3',
 'TET3',
 'CHD2',
 'ATP8B2',
 'PKD1',
 'DLG5',
 'TRIM8',
 'NSMF',
 'SEL1L3',
 'BTAF1',
 'MBTPS1',
 'MAST2',
 'ATXN1',
 'PTPRS',
 'AADAT',
 'SHB',
 'MAN1A2',
 'MYO18B',
 'POMGNT2',
 'SH2B3',
 'GLI3',
 'MAPKAPK5',
 'ATP11A',
 'TNRC6C',
 'CAPN15',
 'SMO',
 'PCNX3',
 'CHD6',
 'DAPK1',
 'ALKBH5',
 'SLC35B2',
 'RAPGEF1',
 'KIFC2',
 'SSH1',
 'ZC3H11A',
 'SPRED1',
 'ZNF324B',
 'UTS2R',
 'DENND4B',
 'KIF26A',
 'ADCY3',
 'KIF1C',
 'ARHGAP39',
 'SBF1',
 'ATXN7L3',
 'FOXN3',
 'LRP8',
 'MAP3K11',
 'PER3',
 'GABBR1',
 'EXT1',
 'RALGDS',
 'HS6ST1',
 'PLXNA1',
 'UBN1',
 'AGBL5',
 'ZFAT',
 'ARHGEF12',
 'TRIO',
 'TTBK2',
 'RBBP8',
 'KIF21B',
 'ARHGAP23',
 'PITPNM2',
 'FOXM1',
 'ZNF71',
 'EFL1',
 'KDM4B',
 'ITGB8',
 'HIPK2',
 'HACE1',
 'ZNF496',
 'ABTB2',
 'TBC1D9',
 'TAB3',
 'CACNA1H',
 'ERCC8',
 'HIRA',
 'DAB2IP',
 'LRRC8B',
 'HIVEP2',
 'IL11',
 'NF2',
 'MARK3',
 'MLLT6',
 'MPRIP',
 'ZNF236',
 'IRS1',
 'ZNF835',
 'PPFIA4',
 'PAPD7',
 'CREBBP',
 'SLC40A1',
 'CDC42BPB',
 'PTPN21',
 'PDE8A',
 'CIC',
 'B4GALNT3',
 'UBE3C',
 'CAMSAP1',
 'EPB41L1',
 'STK11',
 'ST3GAL2',
 'DZIP1',
 'IPO13',
 'JARID2',
 'VPS54',
 'HIVEP3',
 'BRSK1',
 'SLF2',
 'TIAM1',
 'PTPRG',
 'REXO1',
 'B4GALT2',
 'TNK2',
 'TOP3B',
 'RAB11FIP3',
 'GRIN3A',
 'RC3H2',
 'LRP3',
 'GNAZ',
 'CELSR3',
 'FBXW7',
 'CCDC88C',
 'USP31',
 'TMC6',
 'NDST1',
 'PCF11',
 'TULP4',
 'SH3RF3',
 'LATS2',
 'SLC43A1',
 'CUEDC1',
 'TRAK2',
 'PACS2',
 'HOMER2',
 'FBXO41',
 'SHANK3',
 'AZIN1',
 'MED13',
 'FAM20C',
 'SETD1A',
 'ZDHHC6',
 'BRD4',
 'GPBP1L1',
 'SETD5',
 'MTCL1',
 'SIPA1L2',
 'STARD9',
 'SHD',
 'TWNK',
 'SEMA6B',
 'SPTBN2',
 'EP300',
 'CRAMP1',
 'PREX1',
 'PHF2',
 'ADGRL1',
 'SOBP',
 'TRAF3',
 'ARHGEF11',
 'DOCK5',
 'SCN8A',
 'GLI2',
 'NIPA2',
 'MYO9B',
 'TNRC6A',
 'AGAP1',
 'KMT2B']

In [5]:
types = ['rna','rpf','te']
for t in types:
    for i in range(1,5):
        path = 'ChrE/Reads/'+t+str(i)+'.csv'
        df =pd.read_csv(path,sep=',')
        df = df.merge(merged, left_on='Unnamed: 0', right_on='AccNum')
        df['-log10padj']=-np.log10(df['padj'])

        upregulated_genes = df[df['log2FoldChange']>=1]
        upregulated_genes = upregulated_genes[upregulated_genes['-log10padj']>=1]
        downregulated_genes = df[df['log2FoldChange']<=-1]
        downregulated_genes = downregulated_genes[downregulated_genes['-log10padj']>=1]

#         filepath='No_ChrE/Reads/Downregulated/'+t+str(i)+'_accnum.txt'
#         file = open(filepath,"w")     
#         for L in downregulated_genes['Unnamed: 0'].tolist():
#              file.writelines(L+'\n') 

#         filepath='No_ChrE/Reads/Upregulated/'+t+str(i)+'_accnum.txt'
#         file = open(filepath,"w")     
#         for L in upregulated_genes['Unnamed: 0'].tolist():
#              file.writelines(L+'\n') 

#         filepath='No_ChrE/Reads/Downregulated/'+t+str(i)+'_gene.txt'
#         file = open(filepath,"w")     
#         for L in downregulated_genes['GeneName'].tolist():
#              file.writelines(L+'\n') 

#         filepath='No_ChrE/Reads/Upregulated/'+t+str(i)+'_gene.txt'
#         file = open(filepath,"w")     
#         for L in upregulated_genes['GeneName'].tolist():
#              file.writelines(L+'\n') 
#         file.close()      
        print("For",i)
        list_genes = downregulated_genes.nlargest(5, '-log10padj')['GeneName'].tolist()+upregulated_genes.nlargest(5, '-log10padj')['GeneName'].tolist()+['chrE','TRIO','ROCK2']
        print(list_genes)
    #     print(upregulated_genes['GeneName'].tolist()+downregulated_genes['GeneName'].tolist())
    #     print(df[df['GeneName']=='chrE']['-log10padj'])
    #     print(df[df['GeneName']=='chrE']['log2FoldChange'])

For 1
['FOS', 'JUNB', 'EGR1', 'PPP1R15A', 'DUSP1', 'AMOTL2', 'HES1', 'NFATC2', 'NUAK1', 'chrE', 'TRIO', 'ROCK2']
For 2
['JUNB', 'BTG1', 'SERTAD3', 'PPP1R15A', 'ZNF217', 'TXNIP', 'ADM', 'NUAK2', 'AMOTL2', 'HIST1H2AA', 'chrE', 'TRIO', 'ROCK2']
For 3
['JUNB', 'BTG1', 'PPP1R15A', 'ZNF217', 'OSR2', 'chrE', 'TXNIP', 'ADM', 'NUAK2', 'HIST1H2AA', 'chrE', 'TRIO', 'ROCK2']
For 4
['BTG1', 'RGS16', 'OSR2', 'BTG2', 'SERTAD3', 'chrE', 'TXNIP', 'ADM', 'NUAK2', 'ARRDC3', 'chrE', 'TRIO', 'ROCK2']
For 1
['FOS', 'EGR1', 'JUNB', 'JUN', 'DUSP1', 'DKK1', 'SH3BP4', 'LATS2', 'AMOTL2', 'MAP3K11', 'chrE', 'TRIO', 'ROCK2']
For 2
['JUNB', 'MCL1', 'BTG2', 'RGS16', 'RBFOX1', 'chrE', 'PLXNA1', 'SH3BP4', 'LATS2', 'MAP3K11', 'chrE', 'TRIO', 'ROCK2']
For 3
['SOD2', 'JUNB', 'MCL1', 'FOSB', 'PNRC1', 'chrE', 'CAMSAP1', 'LATS2', 'RAPGEF1', 'ADM', 'chrE', 'TRIO', 'ROCK2']
For 4
['KLHL41', 'FOSB', 'S100A13', 'BTG2', 'JUNB', 'chrE', 'CAMSAP1', 'LATS2', 'GIGYF1', 'RAPGEF1', 'chrE', 'TRIO', 'ROCK2']
For 1
['MAP3K11', 'MBTPS1', 'STK11', 'KIF1C', 'PPP1R16A', 'chrE', 'TRIO', 'ROCK2']
For 2
['ATP2A1', 'MAGED2', 'ENO3', 'NAGK', 'COTL1', 'MAP3K11', 'MBTPS1', 'chrE', 'CAMSAP1', 'PLXNA1', 'chrE', 'TRIO', 'ROCK2']
For 3
['MAGED2', 'KLHL41', 'ENO3', 'S100A13', 'DERL1', 'CAMSAP1', 'MBTPS1', 'STK11', 'CHSY1', 'RAPGEF1', 'chrE', 'TRIO', 'ROCK2']
For 4
['KLHL41', 'JUN', 'ASB5', 'Mar-06', 'MAGED2', 'CAMSAP1', 'MBTPS1', 'KIF1C', 'CHSY1', 'RAPGEF1', 'chrE', 'TRIO', 'ROCK2']

In [40]:
df[df['GeneName']=='chrE']

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,AccNum,GeneName,-log10padj
0,chrE,49461.297217,3.116655,0.274907,11.337138,8.590784e-30,8.863971e-26,chrE,chrE,25.052372

In [ ]:
df.head()